### ISSUE TITLE
Log error messages when CLIPS is not found and a fatal error occurs

### ISSUE THREAD

**Issue by Rekkonnect** [algono/clips-ide-vscode#5]
I had been troubleshooting my CLIPS path setting for a few hours when the path was visible and correct. It magically worked after a few restarts, and I never found out how or why it was failing to work. The logs were not available and all I could make up from the code of the extension is that it shows the 'Fatal error. Check if CLIPS is installed.' message upon encountering any error that remains unlogged.

It's generally good practice to log all errors that occur, especially fatal ones that have no clear indication as to why they occur in the first place. Also, including the path in the logs might be helpful to detect potential sync issues with the settings.

**Comment by algono** [comment]
Hi, I just checked this issue. It turns out that VSCode does not output all logs to the console to an output window automatically (as I thought back when I wrote that code), but you have to do it manually.

So I have updated the code so now it logs both to the console and a dedicated "CLIPS" output window.

For context, this was a project I made for fun 2 years ago, and it was my first VSCode extension. So I was learning as I went.

Now I don't have time to maintain this project anymore, so I have added a notice in the README to reflect that the project is no longer being maintained. I will also be both closing this issue and archiving the project. Feel free to fork this project and make it your own if you wish to continue it from here.

Thanks for checking out the project and reporting this issue, I hope the extension was useful to you.
